function eeg_events = convert_events(movement_events)
% function eeg_events = convert_events(movement_events)
%
% Convert events from detect_movement_events.m to a format that can be
% imported into eeglab with pop_importevent.m
%
% Inputs:
%   - movement_events: struct generated by detect_movement_events
% Outputs:
%   - eeg_events: 3xn cell array with columns {type, latency, duration}

types = fieldnames(movement_events);
n_events = 0;
for i = 1:numel(types)
    type = types{i};
    n_events = n_events + movement_events.(type).n_events;
end

eeg_events = cell(n_events,3);

i_event = 1;
for i_type = 1:numel(types)
    type = types{i_type};
    for i = 1:movement_events.(type).n_events
        eeg_events{i_event,1} = [type '_mmt'];
        eeg_events{i_event,2} = movement_events.(type).onset(i) * movement_events.(type).dt;
        eeg_events{i_event,3} = movement_events.(type).duration_s(i);
        i_event = i_event + 1;
    end
end

end