function params = get_params_for_movement_time_series(input_gui)

params = struct('movement_threshold_std', 3.0, ...
    'light_threshold_std', 5.0, ...
    'duration_limit', 40 * 1e-3, ...
    'interval_limit', 500 * 1e-3, ...
    'period_after_end', 500 * 1e-3);

if input_gui

    prompt = {...
        'movement std threshold',...
        'light std threshold',...
        'min event duration (s)',...
        'min time between events (s)',...
        'event decay time (s)'};
    dlgtitle = 'Parameters for movement event detection';
    dims = [1 30];
    definput = {...
        num2str(params.movement_threshold_std), ...
        num2str(params.light_threshold_std), ...
        num2str(params.duration_limit), ...
        num2str(params.interval_limit), ...
        num2str(params.period_after_end)};

    result = inputdlg(prompt, dlgtitle, dims, definput, 'on');

    params.movement_threshold_std = str2num(result{1});
    params.light_threshold_std = str2num(result{2});
    params.duration_limit = str2num(result{3});
    params.interval_limit = str2num(result{4});
    params.period_after_end = str2num(result{5});
end

end