data = test_data(100);
events = process_bursts(data,{'T1','T2','T3'});
assert(abs(events.T1.power - 1e10)/events.T1.power < eps, ...
    ['Expected 0.01 V^2, got ',num2str(events.T1.power, '%8.4e')]);
assert(abs(events.T2.power - 0.0)/events.T1.power < eps, ...
    ['Expected 0.0 V^2, got ',num2str(events.T2.power, '%8.4e')]);
assert(abs(events.T3.power - 1e10)/events.T1.power < eps, ...
    ['Expected 0.01 V^2, got ',num2str(events.T3.power, '%8.4e')]);
disp('Test passed!')